apiVersion: v1
kind: Service
metadata:
  name: smaster-redis-cluster
  namespace: default
  labels:
    app.kubernetes.io/instance: smaster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    helm.sh/chart: redis-cluster-7.0.13
spec:
  ports:
    - name: tcp-redis
      protocol: TCP
      port: 6379
      targetPort: tcp-redis
  selector:
    app.kubernetes.io/instance: smaster
    app.kubernetes.io/name: redis-cluster
  type: ClusterIP
  sessionAffinity: None
